### ISSUE TITLE
Create Github Action for the backend Unit Tests

### ISSUE THREAD

**Issue by Clicky02** [EECE3093C/team-project-golden-girls-backend#95]
### Summary

We have created code for unit tests on the backend, but the tests are not integrated with a GitHub Action.

### Solution

Create a GitHub Action that will run the unit tests in `test/server.js`.

**Comment by ckinateder** [comment]
We need to pay special attention to .env variables

**Comment by ckinateder** [comment]
Going to use Docker and not Compose for this

**Comment by ckinateder** [comment]
Make sure to edit NODE_ENV. Make second secret JUST containing that and DON'T echo into .env on action creation
